service_discovery:
    zk.1: 127.0.0.1:21811
    consul: http://consul-sit.mid.io:8500
    redis.1:
        name: local
xrock_services:
    sylar.top:
        all: fair
grpc_services:
    default:
        recommend-recall: fair
consul:
    register_info:
        Name: test-xxx
        Port: 8080
        Check:
            Interval: 10s
            HTTP: /check
            DeregisterCriticalServiceAfter: 10s
